sm_project/groups/urls.py
########################
## GROUP URLS.PY FILE ##
########################

from django.urls import path
from groups import views

app_name = 'groups'

urlpatterns = [
	path('new/', views.CreateGroup.as_view(), name='create'),
	path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
	path('', views.ListGroups.as_view(), name='all'),
	path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
	path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),
]

sm_project/posts/urls.py
########################
## POSTS URLS.PY FILE ##
########################

from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
	path('', views.PostList.as_view(), name='all'),
	path('by/<username>/', views.UserPost.as_view(), name='for_user'),
	path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
	path('new/', views.CreatePost.as_view(), name='create'),
	path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

sm_project/sm_project/urls.py
from django.contrib import admin
from django.urls import path, include
from sm_project import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', views.HomePage.as_view(), name='home'),
	path('loginpage/', views.LoginPage.as_view(), name='loginpage'),
	path('thankspage/', views.ThanksPage.as_view(), name='thankspage'),
	path('accounts/', include('accounts.urls', namespace='accounts')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('groups/', include('groups.urls', namespace='groups')),
	path('posts/', include('posts.urls', namespace='posts')),
]

sm_project/groups/models.py
##########################
## GROUPS VIEWS.PY FILE ##
##########################

from django.contrib.auth import get_user_model
from django import template
from django.db import models
from django.utils.text import slugify
from misaka import html
from django.urls import reverse

User = get_user_model()
register = template.Library()

class Group(models.Model):

	name = models.CharField(max_length=255, unique=True)
	slug = models.SlugField(allow_unicode=True, unique=True)
	description = models.TextField(blank=True, default="")
	description_html = models.TextField(editable=False, blank=True, default="")
	members = models.ManyToManyField(User, through='GroupMember')

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):

		self.slug = slugify(self.name)
		self.description_html = html(self.description)
		super().save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('groups:single', kwargs={'slug': self.slug})

	class Meta:
		ordering = ['name']

class GroupMember(models.Model):

	user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)
	group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username

	class Meta:

		unique_together = ('user', 'group')

sm_project/groups/views.py
##########################
## GROUPS VIEWS.PY FILE ##
##########################

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from groups.models import Group, GroupMember
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.contrib import messages

class CreateGroup(LoginRequiredMixin, generic.CreateView):

	model = Group
	fields = ('name', 'description')

	def form_valid(self, form):
		
		result = super().form_valid(form)
		GroupMember.objects.create(user=self.request.user, group=self.object)
		return result

class SingleGroup(generic.DetailView):
	model = Group

class ListGroups(generic.ListView):
	model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

		try:
			GroupMember.objects.create(user=self.request.user, group=group)
		except IntegrityError:
			messages.warning(self.request, (f"Warning, already a group member of {group.name} group."))
		else:
			messages.success(self.request, (f"You are now a member of {group.name} Group."))

		return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

	def get(self, request, *args, **kwargs):

		try:
			membership = GroupMember.objects.filter(
				user=self.request.user,
				group__slug=self.kwargs.get('slug')
			).get()
		except GroupMember.DoesNotExist:
			messages.warning(self.request, ("You can't leave this group because you aren't in it!"))
		else:
			membership.delete()
			messages.success(self.request, ("You have successfully left this group."))

		return super().get(request, *args, **kwargs)

sm_project/groups/templates/groups/group_base.html
{% extends 'base.html' %}

	{% block content %}
		<div class="container">
			<div class="row">
				{% block pregroup %} {% endblock %}
				{% block group_content %} {% endblock %}
			</div>
		</div>
	{% endblock %}

sm_project/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

	{% block pregroup %}
		<div class="container">
			<h1>{{ group.name }}</h1>
			<h2>Member Count: {{ group.members.count }}</h2>

			<div class="content">
				{% if user in group.members.all %}
					<a class="btn btn-lg btn-warning" href="{% url 'groups:leave' slug=group.slug %}"><span class="fa fa-times-circle-o"></span>Leave</a>
				{% else %}
					<a class="btn btn-lg btn-warning" href="{% url 'groups:join' slug=group.slug %}"><span class="fa fa-check-circle-o"></span>Join</a>
				{% endif %}
			</div>
		</div>
	{% endblock %}

	{% block group_content %}
		<div class="col-md-8">
			{% if group.posts.count == 0 %}
				<h2>No Post In This Group Yet!</h2>
			{% else %}
				{% for post in group.posts.all %}
					{% include 'posts/_post.html' %}
				{% endfor %}
			{% endif %}
		</div>
	{% endblock %}

sm_project/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

	{% block group_content %}
		<div class="container">
			<h4>Create New Group</h4>

			<form id="groupForm" action="{% url 'groups:create' %}" method="POST">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
					<button type="submit" class="btn btn-large btn-primary">Create</button>
				{% endbuttons %}
			</form>
		</div>
	{% endblock %}

sm_project/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

	{% block pregroup %}
		<div class="col-md-4">
			<div class="content">
				{% if user.is_authenticated %}
					<h2>
						Welcome Back
						<a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
					</h2>
				{% endif %}
				<h2>Groups</h2>
				<p>Welcome to the groups page! <br>Select a group with a shared interest.</p>
			</div>
			{% if user.is_authenticated %}
				<a class="btn btn-warning" href="{% url 'groups:create' %}" role="button"><span class="fa fa-plus"></span>Create New Group</a>
			{% endif %}
		</div>
	{% endblock %}

	{% block group_content %}
		<div class="col-md-8">
			<div class="list-group">
				{% for group in object_list %}
					<a class="list-group-item list-group-item-action flex-column align-items-start" href="{% url 'groups:single' slug=group.slug %}">
						<h3 class="mb-1">{{ group.name }}</h3>
						<p class="mb-1">{{ group.description_html|safe }}</p>
						<div class="d-flex w-40 justify-content-between">
							<small class="text-muted"><span class="badge badge-secondary">{{ group.members.count }}</span>Member{{ group.members.count|pluralize }}</small>
							<small class="text-muted"><span class="badge badge-secondary">{{ group.posts.count }}</span>Post{{ group.posts.count|pluralize }}</small>
							<span><span></span></span>
						</div>
					</a>
				{% endfor %}
			</div>
		</div>
	{% endblock %}